#!/usr/bin/env python3
"""Generate Resources/SampleVase.obj, the scan bundled with the app.

The sample lets App Review, buyers and anyone without a LiDAR iPhone try the whole
prepare-and-export flow. It is built to show what the app is for:

- a foot ring under a recessed base, so the flat-base cut goes through a ring and
  its cap has to leave the centre open;
- a rough underside, standing in for what a real scan reconstructs there, so the
  trim visibly matters.

It is a closed surface of revolution: a profile running from the axis under the
base, round the outside, over the rim and back down the inside to the axis, spun
about the vertical. Written in Object Capture's convention -- metres, Y up -- so
it goes through exactly the loader a real scan does.

    python3 tools/make_sample.py
"""
import math
import random
from pathlib import Path

SEGMENTS = 96
STEP_MM = 1.5

# (radius, height) in mm, from the axis under the base, outwards, up the outside,
# over the rim, down the inside and back to the axis on the inner floor.
PROFILE = [
    (0, 3), (10, 3), (20, 3), (23, 2.5), (24, 0.8), (25, 0), (27, 0), (28.5, 0.5),
    (30, 2), (33, 6), (36, 14), (38, 24), (38.5, 34), (37, 44), (33, 54), (28, 62),
    (24, 70), (22, 78), (22.5, 84), (25, 88), (26, 90), (25, 90.8),
    (24, 89), (21, 84), (20, 78), (22, 70), (26, 62), (31, 54), (35, 44),
    (36.5, 34), (36, 24), (34, 14), (31, 8), (25, 6.5), (15, 6), (0, 6),
]


def refined(profile):
    """Subdivide each profile segment so no step exceeds STEP_MM."""
    out = [profile[0]]
    for (r0, z0), (r1, z1) in zip(profile, profile[1:]):
        n = max(1, math.ceil(math.hypot(r1 - r0, z1 - z0) / STEP_MM))
        out += [(r0 + (r1 - r0) * k / n, z0 + (z1 - z0) * k / n) for k in range(1, n + 1)]
    return out


def build():
    """Vertices (mm, Z up) and outward-wound triangles."""
    rng = random.Random(3)
    profile = refined(PROFILE)
    inner_start = PROFILE.index((25, 90.8))
    rings = []
    vertices = [(0.0, 0.0, profile[0][1])]  # pole under the base
    for i, (r, z) in enumerate(profile[1:-1], start=1):
        ring = []
        # Only the outside of the base is rough: that is the part a scanner sees badly.
        rough = z <= 2.6 and i < len(profile) // 2
        for j in range(SEGMENTS):
            a = 2 * math.pi * j / SEGMENTS
            dz = rng.uniform(-0.3, 0.3) if rough else 0.0
            ring.append(len(vertices))
            vertices.append((r * math.cos(a), r * math.sin(a), max(0.0, z + dz)))
        rings.append(ring)
    top_pole = len(vertices)
    vertices.append((0.0, 0.0, profile[-1][1]))

    faces = []
    first = rings[0]
    for j in range(SEGMENTS):
        faces.append((0, first[(j + 1) % SEGMENTS], first[j]))
    for ra, rb in zip(rings, rings[1:]):
        for j in range(SEGMENTS):
            k = (j + 1) % SEGMENTS
            faces.append((ra[j], ra[k], rb[k]))
            faces.append((ra[j], rb[k], rb[j]))
    last = rings[-1]
    for j in range(SEGMENTS):
        faces.append((top_pole, last[j], last[(j + 1) % SEGMENTS]))

    # Wind outwards whatever the profile's direction: flip if the volume is negative.
    volume = 0.0
    for a, b, c in faces:
        p, q, s = vertices[a], vertices[b], vertices[c]
        volume += (p[0] * (q[1] * s[2] - q[2] * s[1]) - p[1] * (q[0] * s[2] - q[2] * s[0])
                   + p[2] * (q[0] * s[1] - q[1] * s[0])) / 6
    if volume < 0:
        faces = [(a, c, b) for a, b, c in faces]
    return vertices, faces


def main():
    vertices, faces = build()
    out = Path(__file__).resolve().parent.parent / "Resources" / "SampleVase.obj"
    lines = ["# LiDAR Scan 3D sample scan: a vase on a foot ring. Metres, Y up.",
             "# Generated by tools/make_sample.py -- edit that, not this."]
    # Z-up millimetres -> Y-up metres: (x, y, z) -> (x, z, -y), a proper rotation.
    lines += [f"v {x / 1000:.6f} {z / 1000:.6f} {-y / 1000:.6f}" for x, y, z in vertices]
    lines += [f"f {a + 1} {b + 1} {c + 1}" for a, b, c in faces]
    out.write_text("\n".join(lines) + "\n")
    print(f"{out}: {len(vertices)} vertices, {len(faces)} triangles")


if __name__ == "__main__":
    main()
